name: keep-streamlit-awake-b
on:
  schedule:
    - cron: "2-59/5 * * * *"
  workflow_dispatch: {}
jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Ping Streamlit (3 intentos rápidos)
  run: |
    URL="https://app-cochera-vcnrwbnqeobiojf2tggwxc.streamlit.app"
    UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119 Safari/537.36"

    success=0
    for i in 1 2 3; do
      code=$(curl -sS -o /dev/null -w "%{http_code}" \
        --connect-timeout 15 --max-time 45 \
        -H "User-Agent: $UA" -H "Cache-Control: no-cache" \
        "${URL}?t=$(date +%s)")
      echo "Intento $i → HTTP $code"
      # contamos como éxito cualquier 2xx o 3xx (despierta igual)
      if [ "${code:0:1}" = "2" ] || [ "${code:0:1}" = "3" ]; then success=1; fi
      sleep 10
    done

    # no fallar el job si no hubo 2xx/3xx (evita ❌ por intermitencias)
    if [ $success -eq 0 ]; then echo "Sin 2xx/3xx, pero continuamos."; fi


