name: keep-streamlit-awake-b

on:
  schedule:
    - cron: "2-59/5 * * * *"   # min 2,7,12,... (UTC)
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar Playwright
        run: |
          npm i -g playwright
          npx playwright install --with-deps chromium

      - name: Browser ping (despierta Streamlit)
        env:
          URL: "https://app-cochera-vcnrwbnqeobiojf2tggwxc.streamlit.app"
        run: |
          node - <<'JS'
          const { chromium } = require('playwright');
          (async () => {
            const b = await chromium.launch({ headless: true });
            const p = await b.newPage({
              userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119 Safari/537.36'
            });
            // Carga como un usuario real, evita loops de redirección
            await p.goto(process.env.URL + '?keepalive=' + Date.now(), { waitUntil: 'domcontentloaded', timeout: 45000 });
            // Espera breve para garantizar inicio del script
            await p.waitForTimeout(3000);
            await b.close();
          })();
          JS

