name: keep-streamlit-awake

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Ping Streamlit (rápido y redundante)
        run: |
          URL="https://app-cochera-vcnrwbnqeobiojf2tggwxc.streamlit.app/"
          UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119 Safari/537.36"
          for i in 1 2 3; do
            curl -L --silent --show-error --fail \
              --connect-timeout 15 --max-time 45 \
              --retry 4 --retry-delay 5 --retry-max-time 60 --retry-all-errors \
              -H "User-Agent: $UA" -H "Cache-Control: no-cache" \
              "${URL}?t=$(date +%s)" || true
            sleep 10
          done
